-- V047 — cfg_uf_autorizador para as 27 unidades da federação (2026-08-20).
-- Ver docs/MODULOFISCAL.md §F10 e docs/PROGRESSO.md (2026-08-20).
--
-- POR QUE
-- Até aqui a tabela tinha **4 linhas, todas do Paraná** — que é onde a homologação foi feita, não
-- o alcance do produto. O Nainer é vendido para os 26 estados e o Distrito Federal, e
-- `SefazAutorizadorService` responde 409 ("a UF ainda não está cadastrada") para qualquer outra:
-- na prática, um lojista de fora do PR não emitia nada. A arquitetura já estava pronta desde a
-- V034 (F10: "a UF é dado, não código") — faltava o dado.
--
-- 108 linhas = 27 UFs × 2 modelos (55/65) × 2 ambientes (1 produção · 2 homologação).
--
-- FONTES (nenhuma URL foi digitada à mão — o SQL foi gerado a partir destes arquivos)
--   · Roteamento UF→autorizador: `storage/autorizadores.json` do projeto nfephp-org/sped-nfe.
--     ⚠️ O autorizador MUDA COM O MODELO: BA e PE têm autorizador próprio na NF-e 55 e usam a
--     SVRS na NFC-e 65; o MA usa SVAN no 55 e SVRS no 65. Por isso a tabela é chaveada pelos três.
--   · Endpoints: `storage/wsnfe_4.00_mod55.xml` e `wsnfe_4.00_mod65.xml` do mesmo projeto.
--   · Consulta pública da NFC-e (`urlChave` do infNFeSupl): `storage/uri_consulta_nfce.json`.
--   · QR Code: elemento `NfeConsultaQR` do XML do modelo 65, que existe por UF mesmo quando quem
--     autoriza é a SVRS — o endereço de consulta é sempre do estado do emitente.
--   · `codigo_uf_ibge`: mapa do próprio projeto (`ChaveAcesso.CODIGO_UF`). Conferido por teste:
--     `SefazAutorizadorCrudTest` compara linha a linha com o mapa do Java, porque cUF errado
--     produz chave de acesso errada — e a SEFAZ recusa sem explicar que o problema é esse.
--
-- ✅ COMO ESTA CARGA FOI VALIDADA
-- As linhas do PR geradas pela fonte saíram **idênticas** às que a V034 já tinha — e aquelas
-- autorizaram NFC-e e NF-e de verdade contra a SEFAZ-PR (B0, B7, B9). É a melhor evidência
-- disponível sem transmitir para as outras 26: a mesma fonte reproduz, sem ajuste, o que se sabe
-- que funciona. Por isso as 4 linhas do PR são preservadas (ON CONFLICT DO NOTHING): elas
-- carregam observações escritas à mão que valem mais que a carga automática.
--
-- ⚠️ O QUE ESTA MIGRATION **NÃO** AFIRMA
--   · `aliquota_interna` e `aliquota_fcp` ficam NULL. Não são consumidas por nenhum caminho de
--     código (o FCP que entra no cálculo vem de `regra_fiscal`, do perfil fiscal do lojista);
--     preencher 27 alíquotas de memória seria inventar dado tributário.
--   · `exige_cbenef` fica false. Há UF que exige `cBenef` em CST com benefício (RJ e RS são as
--     mais citadas); marcar true sem confirmar quebraria a emissão. Vira `UPDATE` quando cada
--     caso for confirmado na SEFAZ da UF.
--   · `permite_extemporaneo` fica false — cancelamento fora do prazo por via administrativa é
--     exceção, e false é o comportamento seguro (não oferecer um caminho que pode não existir).
--   · `prazo_cancelamento_min`: 1440 no modelo 55 (24 h, Ajuste SINIEF 07/2005, nacional) e 30 no
--     modelo 65 (o prazo mais comum, e o mesmo default que o Java já usava quando a coluna era
--     nula). UF que conceder mais é `UPDATE` de uma linha.
--   · `url_consulta_publica` sai **como cada SEFAZ publica** — parte com esquema (`http://`),
--     parte sem (`www.sefaz.to.gov.br/nfce/consulta`). Não é defeito de carga nem falta de
--     normalização: é o endereço que a UF divulga, e é ele que o consumidor vê impresso no
--     DANFE NFC-e. Não "consertar" acrescentando esquema sem confirmar na SEFAZ da UF.
--   · Endereço de webservice muda sem aviso. Antes de ligar a primeira emissão de uma UF nova,
--     bata o `url_status_servico` dela — é o serviço mais barato e não gera documento.

INSERT INTO cfg_uf_autorizador (
  uf, modelo, ambiente, codigo_uf_ibge, autorizador,
  url_autorizacao, url_ret_autorizacao, url_status_servico,
  url_recepcao_evento, url_inutilizacao, url_consulta_protocolo,
  url_qrcode, url_consulta_publica,
  prazo_cancelamento_min, prazo_contingencia_horas,
  aliquota_interna, aliquota_fcp, exige_cbenef, permite_extemporaneo, exige_csrt,
  observacao
) VALUES
  ('AC', 55, 1, 12, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AC', 55, 2, 12, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AC', 65, 1, 12, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.sefaznet.ac.gov.br/nfce/qrcode', 'www.sefaznet.ac.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('AC', 65, 2, 12, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.hml.sefaznet.ac.gov.br/nfce/qrcode', 'www.sefaznet.ac.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('AL', 55, 1, 27, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AL', 55, 2, 27, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AL', 65, 1, 27, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfce.sefaz.al.gov.br/QRCode/consultarNFCe.jsp', 'www.sefaz.al.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('AL', 65, 2, 27, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfce.sefaz.al.gov.br/QRCode/consultarNFCe.jsp', 'www.sefaz.al.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('AM', 55, 1, 13, 'PROPRIO',
   'https://nfe.sefaz.am.gov.br/services2/services/NfeAutorizacao4',
   'https://nfe.sefaz.am.gov.br/services2/services/NfeRetAutorizacao4',
   'https://nfe.sefaz.am.gov.br/services2/services/NfeStatusServico4',
   'https://nfe.sefaz.am.gov.br/services2/services/RecepcaoEvento4',
   'https://nfe.sefaz.am.gov.br/services2/services/NfeInutilizacao4',
   'https://nfe.sefaz.am.gov.br/services2/services/NfeConsulta4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AM', 55, 2, 13, 'PROPRIO',
   'https://homnfe.sefaz.am.gov.br/services2/services/NfeAutorizacao4',
   'https://homnfe.sefaz.am.gov.br/services2/services/NfeRetAutorizacao4',
   'https://homnfe.sefaz.am.gov.br/services2/services/NfeStatusServico4',
   'https://homnfe.sefaz.am.gov.br/services2/services/RecepcaoEvento4',
   'https://homnfe.sefaz.am.gov.br/services2/services/NfeInutilizacao4',
   'https://homnfe.sefaz.am.gov.br/services2/services/NfeConsulta4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AM', 65, 1, 13, 'PROPRIO',
   'https://nfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao4',
   'https://nfce.sefaz.am.gov.br/nfce-services/services/NfeRetAutorizacao4',
   'https://nfce.sefaz.am.gov.br/nfce-services/services/NfeStatusServico4',
   'https://nfce.sefaz.am.gov.br/nfce-services/services/RecepcaoEvento4',
   'https://nfce.sefaz.am.gov.br/nfce-services/services/NfeInutilizacao4',
   'https://nfce.sefaz.am.gov.br/nfce-services/services/NfeConsulta4',
   'https://sistemas.sefaz.am.gov.br/nfceweb/consultarNFCe.jsp', 'www.sefaz.am.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('AM', 65, 2, 13, 'PROPRIO',
   'https://homnfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao4',
   'https://homnfce.sefaz.am.gov.br/nfce-services/services/NfeRetAutorizacao4',
   'https://homnfce.sefaz.am.gov.br/nfce-services/services/NfeStatusServico4',
   'https://homnfce.sefaz.am.gov.br/nfce-services/services/RecepcaoEvento4',
   'https://homnfce.sefaz.am.gov.br/nfce-services/services/NfeInutilizacao4',
   'https://homnfce.sefaz.am.gov.br/nfce-services/services/NfeConsulta4',
   'https://sistemas.sefaz.am.gov.br/nfceweb-hom/consultarNFCe.jsp', 'www.sefaz.am.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('AP', 55, 1, 16, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AP', 55, 2, 16, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('AP', 65, 1, 16, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://www.sefaz.ap.gov.br/nfce/nfcep.php', 'www.sefaz.ap.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('AP', 65, 2, 16, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://www.sefaz.ap.gov.br/nfcehml/nfce.php', 'www.sefaz.ap.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('BA', 55, 1, 29, 'PROPRIO',
   'https://nfe.sefaz.ba.gov.br/webservices/NFeAutorizacao4/NFeAutorizacao4.asmx',
   'https://nfe.sefaz.ba.gov.br/webservices/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx',
   'https://nfe.sefaz.ba.gov.br/webservices/NFeStatusServico4/NFeStatusServico4.asmx',
   'https://nfe.sefaz.ba.gov.br/webservices/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
   'https://nfe.sefaz.ba.gov.br/webservices/NFeInutilizacao4/NFeInutilizacao4.asmx',
   'https://nfe.sefaz.ba.gov.br/webservices/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('BA', 55, 2, 29, 'PROPRIO',
   'https://hnfe.sefaz.ba.gov.br/webservices/NFeAutorizacao4/NFeAutorizacao4.asmx',
   'https://hnfe.sefaz.ba.gov.br/webservices/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx',
   'https://hnfe.sefaz.ba.gov.br/webservices/NFeStatusServico4/NFeStatusServico4.asmx',
   'https://hnfe.sefaz.ba.gov.br/webservices/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
   'https://hnfe.sefaz.ba.gov.br/webservices/NFeInutilizacao4/NFeInutilizacao4.asmx',
   'https://hnfe.sefaz.ba.gov.br/webservices/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('BA', 65, 1, 29, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfe.sefaz.ba.gov.br/servicos/nfce/qrcode.aspx', 'http://www.sefaz.ba.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('BA', 65, 2, 29, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://hnfe.sefaz.ba.gov.br/servicos/nfce/qrcode.aspx', 'http://hinternet.sefaz.ba.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('CE', 55, 1, 23, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('CE', 55, 2, 23, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('CE', 65, 1, 23, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfce.sefaz.ce.gov.br/pages/ShowNFCe.html', 'www.sefaz.ce.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('CE', 65, 2, 23, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfceh.sefaz.ce.gov.br/pages/ShowNFCe.html', 'www.sefaz.ce.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('DF', 55, 1, 53, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('DF', 55, 2, 53, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('DF', 65, 1, 53, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.fazenda.df.gov.br/nfce/qrcode', 'www.fazenda.df.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('DF', 65, 2, 53, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx', 'www.fazenda.df.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('ES', 55, 1, 32, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('ES', 55, 2, 32, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('ES', 65, 1, 32, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://app.sefaz.es.gov.br/ConsultaNFCe/qrcode.aspx', 'www.sefaz.es.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('ES', 65, 2, 32, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://homologacao.sefaz.es.gov.br/ConsultaNFCe/qrcode.aspx', 'www.sefaz.es.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('GO', 55, 1, 52, 'PROPRIO',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeAutorizacao4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeRetAutorizacao4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeStatusServico4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeRecepcaoEvento4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeInutilizacao4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('GO', 55, 2, 52, 'PROPRIO',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeAutorizacao4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeRetAutorizacao4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeStatusServico4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeRecepcaoEvento4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeInutilizacao4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('GO', 65, 1, 52, 'PROPRIO',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeAutorizacao4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeRetAutorizacao4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeStatusServico4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeRecepcaoEvento4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeInutilizacao4',
   'https://nfe.sefaz.go.gov.br/nfe/services/NFeConsultaProtocolo4',
   'https://nfeweb.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe', 'www.sefaz.go.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('GO', 65, 2, 52, 'PROPRIO',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeAutorizacao4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeRetAutorizacao4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeStatusServico4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeRecepcaoEvento4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeInutilizacao4',
   'https://homolog.sefaz.go.gov.br/nfe/services/NFeConsultaProtocolo4',
   'https://nfewebhomolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe', 'www.nfce.go.gov.br/post/ver/214413/consulta-nfc-e-homologacao',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MA', 55, 1, 21, 'SVAN',
   'https://www.sefazvirtual.fazenda.gov.br/NFeAutorizacao4/NFeAutorizacao4.asmx',
   'https://www.sefazvirtual.fazenda.gov.br/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx',
   'https://www.sefazvirtual.fazenda.gov.br/NFeStatusServico4/NFeStatusServico4.asmx',
   'https://www.sefazvirtual.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
   'https://www.sefazvirtual.fazenda.gov.br/NFeInutilizacao4/NFeInutilizacao4.asmx',
   'https://www.sefazvirtual.fazenda.gov.br/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVAN. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MA', 55, 2, 21, 'SVAN',
   'https://hom.sefazvirtual.fazenda.gov.br/NFeAutorizacao4/NFeAutorizacao4.asmx',
   'https://hom.sefazvirtual.fazenda.gov.br/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx',
   'https://hom.sefazvirtual.fazenda.gov.br/NFeStatusServico4/NFeStatusServico4.asmx',
   'https://hom.sefazvirtual.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
   'https://hom.sefazvirtual.fazenda.gov.br/NFeInutilizacao4/NFeInutilizacao4.asmx',
   'https://hom.sefazvirtual.fazenda.gov.br/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVAN. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MA', 65, 1, 21, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp', 'www.sefaz.ma.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MA', 65, 2, 21, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.hom.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp', 'www.sefaz.ma.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MG', 55, 1, 31, 'PROPRIO',
   'https://nfe.fazenda.mg.gov.br/nfe2/services/NFeAutorizacao4',
   'https://nfe.fazenda.mg.gov.br/nfe2/services/NFeRetAutorizacao4',
   'https://nfe.fazenda.mg.gov.br/nfe2/services/NFeStatusServico4',
   'https://nfe.fazenda.mg.gov.br/nfe2/services/NFeRecepcaoEvento4',
   'https://nfe.fazenda.mg.gov.br/nfe2/services/NFeInutilizacao4',
   'https://nfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MG', 55, 2, 31, 'PROPRIO',
   'https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeAutorizacao4',
   'https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeRetAutorizacao4',
   'https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeStatusServico4',
   'https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeRecepcaoEvento4',
   'https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeInutilizacao4',
   'https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MG', 65, 1, 31, 'PROPRIO',
   'https://nfce.fazenda.mg.gov.br/nfce/services/NFeAutorizacao4',
   'https://nfce.fazenda.mg.gov.br/nfce/services/NFeRetAutorizacao4',
   'https://nfce.fazenda.mg.gov.br/nfce/services/NFeStatusServico4',
   'https://nfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4',
   'https://nfce.fazenda.mg.gov.br/nfce/services/NFeInutilizacao4',
   'https://nfce.fazenda.mg.gov.br/nfce/services/NFeConsultaProtocolo4',
   'https://portalsped.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml', 'https://portalsped.fazenda.mg.gov.br/portalnfce',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MG', 65, 2, 31, 'PROPRIO',
   'https://hnfce.fazenda.mg.gov.br/nfce/services/NFeAutorizacao4',
   'https://hnfce.fazenda.mg.gov.br/nfce/services/NFeRetAutorizacao4',
   'https://hnfce.fazenda.mg.gov.br/nfce/services/NFeStatusServico4',
   'https://hnfce.fazenda.mg.gov.br/nfce/services/NFeRecepcaoEvento4',
   'https://hnfce.fazenda.mg.gov.br/nfce/services/NFeInutilizacao4',
   'https://hnfce.fazenda.mg.gov.br/nfce/services/NFeConsultaProtocolo4',
   'https://portalsped.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml', 'https://hportalsped.fazenda.mg.gov.br/portalnfce',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MS', 55, 1, 50, 'PROPRIO',
   'https://nfe.sefaz.ms.gov.br/ws/NFeAutorizacao4',
   'https://nfe.sefaz.ms.gov.br/ws/NFeRetAutorizacao4',
   'https://nfe.sefaz.ms.gov.br/ws/NFeStatusServico4',
   'https://nfe.sefaz.ms.gov.br/ws/NFeRecepcaoEvento4',
   'https://nfe.sefaz.ms.gov.br/ws/NFeInutilizacao4',
   'https://nfe.sefaz.ms.gov.br/ws/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MS', 55, 2, 50, 'PROPRIO',
   'https://hom.nfe.sefaz.ms.gov.br/ws/NFeAutorizacao4',
   'https://hom.nfe.sefaz.ms.gov.br/ws/NFeRetAutorizacao4',
   'https://hom.nfe.sefaz.ms.gov.br/ws/NFeStatusServico4',
   'https://hom.nfe.sefaz.ms.gov.br/ws/NFeRecepcaoEvento4',
   'https://hom.nfe.sefaz.ms.gov.br/ws/NFeInutilizacao4',
   'https://hom.nfe.sefaz.ms.gov.br/ws/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MS', 65, 1, 50, 'PROPRIO',
   'https://nfce.sefaz.ms.gov.br/ws/NFeAutorizacao4',
   'https://nfce.sefaz.ms.gov.br/ws/NFeRetAutorizacao4',
   'https://nfce.sefaz.ms.gov.br/ws/NFeStatusServico4',
   'https://nfce.sefaz.ms.gov.br/ws/NFeRecepcaoEvento4',
   'https://nfce.sefaz.ms.gov.br/ws/NFeInutilizacao4',
   'https://nfce.sefaz.ms.gov.br/ws/NFeConsultaProtocolo4',
   'http://www.dfe.ms.gov.br/nfce/qrcode', 'http://www.dfe.ms.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MS', 65, 2, 50, 'PROPRIO',
   'https://hom.nfce.sefaz.ms.gov.br/ws/NFeAutorizacao4',
   'https://hom.nfce.sefaz.ms.gov.br/ws/NFeRetAutorizacao4',
   'https://hom.nfce.sefaz.ms.gov.br/ws/NFeStatusServico4',
   'https://hom.nfce.sefaz.ms.gov.br/ws/NFeRecepcaoEvento4',
   'https://hom.nfce.sefaz.ms.gov.br/ws/NFeInutilizacao4',
   'https://hom.nfce.sefaz.ms.gov.br/ws/NFeConsultaProtocolo4',
   'http://www.dfe.ms.gov.br/nfce/qrcode', 'http://www.dfe.ms.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MT', 55, 1, 51, 'PROPRIO',
   'https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao4',
   'https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao4',
   'https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4',
   'https://nfe.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento4',
   'https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao4',
   'https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MT', 55, 2, 51, 'PROPRIO',
   'https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao4',
   'https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao4',
   'https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4',
   'https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento4',
   'https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao4',
   'https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('MT', 65, 1, 51, 'PROPRIO',
   'https://nfce.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao4',
   'https://nfce.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao4',
   'https://nfce.sefaz.mt.gov.br/nfcews/services/NfeStatusServico4',
   'https://nfce.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento4',
   'https://nfce.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao4',
   'https://nfce.sefaz.mt.gov.br/nfcews/services/NfeConsulta4',
   'http://www.sefaz.mt.gov.br/nfce/consultanfce', 'http://www.sefaz.mt.gov.br/nfce/consultanfce',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('MT', 65, 2, 51, 'PROPRIO',
   'https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao4',
   'https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao4',
   'https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeStatusServico4',
   'https://homologacao.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento4',
   'https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao4',
   'https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeConsulta4',
   'http://homologacao.sefaz.mt.gov.br/nfce/consultanfce', 'http://homologacao.sefaz.mt.gov.br/nfce/consultanfce',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PA', 55, 1, 15, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PA', 55, 2, 15, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PA', 65, 1, 15, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://appnfc.sefa.pa.gov.br/portal/view/consultas/nfce/nfceForm.seam', 'www.sefa.pa.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PA', 65, 2, 15, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://appnfc.sefa.pa.gov.br/portal-homologacao/view/consultas/nfce/nfceForm.seam', 'www.sefa.pa.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PB', 55, 1, 25, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PB', 55, 2, 25, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PB', 65, 1, 25, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.sefaz.pb.gov.br/nfce', 'www.sefaz.pb.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PB', 65, 2, 25, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.sefaz.pb.gov.br/nfcehom', 'www.sefaz.pb.gov.br/nfcehom',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PE', 55, 1, 26, 'PROPRIO',
   'https://nfe.sefaz.pe.gov.br/nfe-service/services/NFeAutorizacao4',
   'https://nfe.sefaz.pe.gov.br/nfe-service/services/NFeRetAutorizacao4',
   'https://nfe.sefaz.pe.gov.br/nfe-service/services/NFeStatusServico4',
   'https://nfe.sefaz.pe.gov.br/nfe-service/services/NFeRecepcaoEvento4',
   'https://nfe.sefaz.pe.gov.br/nfe-service/services/NFeInutilizacao4',
   'https://nfe.sefaz.pe.gov.br/nfe-service/services/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PE', 55, 2, 26, 'PROPRIO',
   'https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeAutorizacao4',
   'https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeRetAutorizacao4',
   'https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeStatusServico4',
   'https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeRecepcaoEvento4',
   'https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeInutilizacao4',
   'https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PE', 65, 1, 26, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfce.sefaz.pe.gov.br/nfce/consulta', 'nfce.sefaz.pe.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PE', 65, 2, 26, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfcehomolog.sefaz.pe.gov.br/nfce/consulta', 'nfce.sefaz.pe.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PI', 55, 1, 22, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PI', 55, 2, 22, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PI', 65, 1, 22, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.sefaz.pi.gov.br/nfce/qrcode', 'www.sefaz.pi.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PI', 65, 2, 22, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.sefaz.pi.gov.br/nfce/qrcode', 'www.sefaz.pi.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PR', 55, 1, 41, 'PROPRIO',
   'https://nfe.sefa.pr.gov.br/nfe/NFeAutorizacao4',
   'https://nfe.sefa.pr.gov.br/nfe/NFeRetAutorizacao4',
   'https://nfe.sefa.pr.gov.br/nfe/NFeStatusServico4',
   'https://nfe.sefa.pr.gov.br/nfe/NFeRecepcaoEvento4',
   'https://nfe.sefa.pr.gov.br/nfe/NFeInutilizacao4',
   'https://nfe.sefa.pr.gov.br/nfe/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PR', 55, 2, 41, 'PROPRIO',
   'https://homologacao.nfe.sefa.pr.gov.br/nfe/NFeAutorizacao4',
   'https://homologacao.nfe.sefa.pr.gov.br/nfe/NFeRetAutorizacao4',
   'https://homologacao.nfe.sefa.pr.gov.br/nfe/NFeStatusServico4',
   'https://homologacao.nfe.sefa.pr.gov.br/nfe/NFeRecepcaoEvento4',
   'https://homologacao.nfe.sefa.pr.gov.br/nfe/NFeInutilizacao4',
   'https://homologacao.nfe.sefa.pr.gov.br/nfe/NFeConsultaProtocolo4',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('PR', 65, 1, 41, 'PROPRIO',
   'https://nfce.sefa.pr.gov.br/nfce/NFeAutorizacao4',
   'https://nfce.sefa.pr.gov.br/nfce/NFeRetAutorizacao4',
   'https://nfce.sefa.pr.gov.br/nfce/NFeStatusServico4',
   'https://nfce.sefa.pr.gov.br/nfce/NFeRecepcaoEvento4',
   'https://nfce.sefa.pr.gov.br/nfce/NFeInutilizacao4',
   'https://nfce.sefa.pr.gov.br/nfce/NFeConsultaProtocolo4',
   'http://www.fazenda.pr.gov.br/nfce/qrcode', 'http://www.fazenda.pr.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('PR', 65, 2, 41, 'PROPRIO',
   'https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeAutorizacao4',
   'https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeRetAutorizacao4',
   'https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeStatusServico4',
   'https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeRecepcaoEvento4',
   'https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeInutilizacao4',
   'https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeConsultaProtocolo4',
   'http://www.fazenda.pr.gov.br/nfce/qrcode', 'http://www.fazenda.pr.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RJ', 55, 1, 33, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RJ', 55, 2, 33, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RJ', 65, 1, 33, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://consultadfe.fazenda.rj.gov.br/consultaNFCe/QRCode', 'www.fazenda.rj.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RJ', 65, 2, 33, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode', 'www.fazenda.rj.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RN', 55, 1, 24, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RN', 55, 2, 24, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RN', 65, 1, 24, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://nfce.set.rn.gov.br/consultarNFCe.aspx', 'www.set.rn.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RN', 65, 2, 24, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://hom.nfce.set.rn.gov.br/consultarNFCe.aspx', 'www.set.rn.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RO', 55, 1, 11, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RO', 55, 2, 11, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RO', 65, 1, 11, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.nfce.sefin.ro.gov.br/consultanfce/consulta.jsp', 'www.sefin.ro.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RO', 65, 2, 11, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.nfce.sefin.ro.gov.br/consultanfce/consulta.jsp', 'www.sefin.ro.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RR', 55, 1, 14, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RR', 55, 2, 14, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RR', 65, 1, 14, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://www.sefaz.rr.gov.br/servlet/qrcode', 'www.sefaz.rr.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RR', 65, 2, 14, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://200.174.88.103:8080/nfce/servlet/qrcode', 'www.sefaz.rr.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RS', 55, 1, 43, 'PROPRIO',
   'https://nfe.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RS', 55, 2, 43, 'PROPRIO',
   'https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('RS', 65, 1, 43, 'PROPRIO',
   'https://nfce.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx', 'www.sefaz.rs.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('RS', 65, 2, 43, 'PROPRIO',
   'https://nfce-homologacao.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx', 'www.sefaz.rs.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('SC', 55, 1, 42, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('SC', 55, 2, 42, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('SC', 65, 1, 42, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://sat.sef.sc.gov.br/nfce/consulta', 'https://sat.sef.sc.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('SC', 65, 2, 42, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'https://hom.sat.sef.sc.gov.br/nfce/consulta', 'https://hom.sat.sef.sc.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('SE', 55, 1, 28, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('SE', 55, 2, 28, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('SE', 65, 1, 28, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.nfce.se.gov.br/nfce/qrcode', 'http://www.nfce.se.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('SE', 65, 2, 28, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.hom.nfe.se.gov.br/nfce/qrcode', 'http://www.hom.nfe.se.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('SP', 55, 1, 35, 'PROPRIO',
   'https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx',
   'https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx',
   'https://nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx',
   'https://nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx',
   'https://nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx',
   'https://nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('SP', 55, 2, 35, 'PROPRIO',
   'https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx',
   'https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx',
   'https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx',
   'https://homologacao.nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx',
   'https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx',
   'https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('SP', 65, 1, 35, 'PROPRIO',
   'https://nfce.fazenda.sp.gov.br/ws/NFeAutorizacao4.asmx',
   'https://nfce.fazenda.sp.gov.br/ws/NFeRetAutorizacao4.asmx',
   'https://nfce.fazenda.sp.gov.br/ws/NFeStatusServico4.asmx',
   'https://nfce.fazenda.sp.gov.br/ws/NFeRecepcaoEvento4.asmx',
   'https://nfce.fazenda.sp.gov.br/ws/NFeInutilizacao4.asmx',
   'https://nfce.fazenda.sp.gov.br/ws/NFeConsultaProtocolo4.asmx',
   'https://www.nfce.fazenda.sp.gov.br/qrcode', 'https://www.nfce.fazenda.sp.gov.br/NFCeConsultaPublica',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('SP', 65, 2, 35, 'PROPRIO',
   'https://homologacao.nfce.fazenda.sp.gov.br/ws/NFeAutorizacao4.asmx',
   'https://homologacao.nfce.fazenda.sp.gov.br/ws/NFeRetAutorizacao4.asmx',
   'https://homologacao.nfce.fazenda.sp.gov.br/ws/NFeStatusServico4.asmx',
   'https://homologacao.nfce.fazenda.sp.gov.br/ws/NFeRecepcaoEvento4.asmx',
   'https://homologacao.nfce.fazenda.sp.gov.br/ws/NFeInutilizacao4.asmx',
   'https://homologacao.nfce.fazenda.sp.gov.br/ws/NFeConsultaProtocolo4.asmx',
   'https://www.homologacao.nfce.fazenda.sp.gov.br/qrcode', 'https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador PROPRIO. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('TO', 55, 1, 17, 'SVRS',
   'https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('TO', 55, 2, 17, 'SVRS',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   NULL, NULL,
   1440, NULL, NULL, NULL, false, false, true,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod55.xml.'),
  ('TO', 65, 1, 17, 'SVRS',
   'https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://www.sefaz.to.gov.br/nfce/qrcode', 'www.sefaz.to.gov.br/nfce/consulta',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.'),
  ('TO', 65, 2, 17, 'SVRS',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
   'https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx',
   'http://homologacao.sefaz.to.gov.br/nfce/qrcode', 'http://homologacao.sefaz.to.gov.br/nfce/consulta.jsf',
   30, 24, NULL, NULL, false, false, false,
   'Carga V047 (2026-08-20). Autorizador SVRS. WS: sped-nfe wsnfe_4.00_mod65.xml; consulta publica: uri_consulta_nfce.json.')
ON CONFLICT (uf, modelo, ambiente) DO NOTHING;
