-- V074 — Catálogo de telas: grupo passa a levar o CAMINHO (2026-08-27)
--
-- ⚠️ Na V073 o grupo era só o rótulo do subgrupo, e isso juntou coisas que não têm relação:
-- "Posição de Estoque" (relatório) caiu no mesmo grupo de "Entrada de Produtos" (operação),
-- porque os dois subgrupos se chamam "Estoque". O dono do produto viu na tela: "faltou o menu
-- de Relatórios que não tem na tela de permissões" — ele não faltava, estava diluído.
--
-- Agora o grupo é o caminho ("Relatórios › Estoque"), que é como o lojista enxerga no menu.
-- ⚠️ Só o rótulo muda: as chaves são as mesmas, então nenhuma permissão já concedida se perde.

INSERT INTO cfg_tela (chave, nome, grupo, ordem, admin_apenas) VALUES
  ('pdv', 'PDV - Vendas', 'Frente de Loja', 1, false),
  ('expedicao', 'Fila de Expedição', 'Frente de Loja', 2, false),
  ('orcamentos', 'Orçamentos', 'Frente de Loja', 3, false),
  ('pesquisa-vendas', 'Pesquisa de Vendas', 'Frente de Loja', 4, false),
  ('recebimento-crediario', 'Recebimento de Crediário', 'Frente de Loja', 5, false),
  ('reimpressao-recebimento-crediario', 'Reimpressão de Recebimento de Crediário', 'Frente de Loja', 6, false),
  ('devolucao-produto', 'Devolução de Produtos', 'Frente de Loja', 7, false),
  ('fechamento-caixa', 'Fechamento de Caixa', 'Frente de Loja', 8, false),
  ('estorno-recebimento-crediario', 'Estorno de Crediário', 'Cancelamentos', 9, false),
  ('cancelamento-devolucao-produtos', 'Cancelamento de Devolução de Produtos', 'Cancelamentos', 10, false),
  ('entrada-produtos-compra', 'Entrada de Produtos por Compra', 'Estoque', 11, false),
  ('estoque.devolucao-compra', 'Devolução de Produtos Comprados', 'Estoque', 12, false),
  ('estoque', 'Transferência de Produtos', 'Estoque', 13, false),
  ('estoque.contagem', 'Contagem de Estoque', 'Contagem de Estoque', 14, false),
  ('estoque.diferencas', 'Diferenças de Estoque', 'Contagem de Estoque', 15, false),
  ('estoque.efetivar-balanco', 'Efetivar Balanço', 'Contagem de Estoque', 16, false),
  ('estoque.zerar-contagem', 'Zerar Contagem de Estoque', 'Contagem de Estoque', 17, false),
  ('contas-corrente', 'Conta Corrente', 'Financeiro', 18, false),
  ('contas-corrente-movimento', 'Movimentação de Conta Corrente', 'Financeiro', 19, false),
  ('planos-contas', 'Plano de Contas', 'Financeiro', 20, false),
  ('tipos-carteira', 'Tipo de Carteira', 'Financeiro', 21, false),
  ('contas-pagar', 'Contas a Pagar / Pagas', 'Financeiro', 22, false),
  ('clientes', 'Clientes', 'Cadastros', 23, false),
  ('fornecedores', 'Fornecedores', 'Cadastros', 24, false),
  ('funcionarios', 'Funcionários', 'Cadastros', 25, false),
  ('produtos', 'Produtos', 'Cadastros', 26, false),
  ('canais', 'Canais de Venda', 'Configurações', 27, true),
  ('minha-conta', 'Minha Conta', 'Configurações', 28, true),
  ('usuarios', 'Usuários', 'Configurações', 29, true),
  ('empresas', 'Empresas', 'Configurações', 30, true),
  ('configuracoes-gerais', 'Parâmetros do Sistema', 'Configurações', 31, true),
  ('etiqueta-configuracao', 'Configuração de Etiqueta de Produtos', 'Configurações', 32, true),
  ('importacao-dados.clientes', 'Clientes', 'Importação de Dados', 33, false),
  ('importacao-dados.contas-receber', 'Contas a Receber', 'Importação de Dados', 34, false),
  ('importacao-dados.fornecedores', 'Fornecedores', 'Importação de Dados', 35, false),
  ('importacao-dados.produtos', 'Produtos', 'Importação de Dados', 36, false),
  ('importacao-dados.estoque', 'Estoque Inicial', 'Importação de Dados', 37, false),
  ('exportacao-dados', 'Exportação de Dados', 'Importação de Dados', 38, false),
  ('fiscal.configuracao', 'Configuração Fiscal', 'Fiscal', 39, false),
  ('fiscal.perfis', 'Perfis Fiscais', 'Fiscal', 40, false),
  ('fiscal.certificados', 'Certificado Digital', 'Fiscal', 41, false),
  ('fiscal.conformidade', 'Conformidade Fiscal', 'Fiscal', 42, false),
  ('fiscal.contingencia', 'Contingência Fiscal', 'Fiscal', 43, false),
  ('fiscal.documentos', 'Documentos Fiscais', 'Fiscal', 44, false),
  ('fiscal.exportacao-xml', 'Exportação de XML em Lote', 'Fiscal', 45, false),
  ('fiscal.inutilizacao', 'Inutilização de Numeração', 'Fiscal', 46, false),
  ('relatorio-vendas', 'Vendas', 'Relatórios › Faturamento', 47, false),
  ('relatorio-comissoes', 'Comissões', 'Relatórios › Faturamento', 48, false),
  ('relatorio-estoque', 'Posição de Estoque', 'Relatórios › Estoque', 49, false),
  ('relatorio-movimentacao-produtos', 'Movimentação de Produtos', 'Relatórios › Estoque', 50, false),
  ('etiqueta-emissao', 'Etiquetas de Produtos', 'Relatórios › Estoque', 51, false),
  ('relatorio-contas-receber', 'Contas a Receber / Recebidas', 'Relatórios › Financeiro', 52, false),
  ('relatorio-contas-pagar', 'Contas a Pagar / Pagas', 'Relatórios › Financeiro', 53, false),
  ('fluxo-caixa', 'Fluxo de Caixa', 'Relatórios › Financeiro', 54, false),
  ('relatorio-dre', 'DRE — Demonstração do Resultado', 'Relatórios › Resultados', 55, true),
  ('lucratividade', 'Lucratividade', 'Relatórios › Resultados', 56, true),
  ('crm', 'CRM', 'Relatórios › Resultados', 57, false),
  ('painel', 'Painel', 'Implementações Futuras', 58, false),
  ('pedidos', 'Pedidos', 'Implementações Futuras', 59, false),
  ('bi-dashboard', 'BI Dashboard', 'Implementações Futuras', 60, false),
  ('relatorio-movimentacao-bancaria', 'Relatório de Movimentação Bancária', 'Implementações Futuras', 61, false),
  ('integracao-marketplace', 'Integração com Marketplace', 'Implementações Futuras', 62, false),
  ('cobranca-crediario-atraso', 'Cobrança de Crediário em Atraso', 'Implementações Futuras', 63, false)
ON CONFLICT (chave) DO UPDATE
  SET nome = EXCLUDED.nome, grupo = EXCLUDED.grupo, ordem = EXCLUDED.ordem,
      admin_apenas = EXCLUDED.admin_apenas;
